### ISSUE TITLE
Need to be able to hit enter to submit. 

### ISSUE THREAD

**Issue by redelste** [redelste/react-flask-todo#1]
On our form we have a "submit button". A user should be able to hit enter after filling out required fields in order to submit, in addition to the button click.

**Comment by khayyamsaleem** [comment]
https://github.com/redelste/react-flask-todo/blob/19c37bcda30904870aba2884d595f627c5e1129e/src/App.js#L40

That line has access to all your required state variables to make your post. To do this properly, we'll want to contain your button in a form, change the button's type to submit, and make the submitAction of the form send your post request.

the last bit there would look like:

```javascript
<form onSubmit={ (e) => handleSubmit(e, newTodo, newDescription, setTodos)}>
// ...
</form>
```

where `handleSubmit` looks like:

```javascript
const handleSubmit = (e, newTodo, newDescription, setTodos) => {
    e.preventDefault();
    if (newTodo) {
        addTodo(newTodo, newDescription, (data) => {
            setTodos([
              ...todos,
              { id:data.id, datecreated: data.datecreated, name:newTodo, description:newDescription }
            ])
        })
    } else {
        alert("Must enter a name for your new todo!")
    }
}
```

**Comment by khayyamsaleem** [comment]
Basically, the key thing here is that we have to ensure that we're giving every function the resources it needs to be able to do its work. For `handleSubmit`, it needed:
- the submit event (`e`)
- the new todo (`newTodo`)
- the new todo's description (`newDescription`)
- the ability to update the list of todos with the new todo it just made (`setTodos`).

`handleSubmit` needed the submit event (`e`) so that it could prevent the default submit behavior (refreshing the page). This was provided to us by the `onSubmit` event listener.

Similarly, the `handleSubmit` function needed access to the `newTodo` and the `newDescription` to be able to send them to your backend (via your existing `addTodo` method). These were state variables declared inside your component definition.

Lastly, we're passing `setTodos` as a callback so that the `handleSubmit` function has access to update the state when it needs to add the new todo. `setTodos` also came from inside your component definition.

Since the `handleSubmit` function is outside your component definition, the only way it can get access to all these things is through arguments. So we pass them from the place where they're known (your component definition) as arguments into the place where they are NOT in scope (your `handleSubmit` function).
